---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-ingress
  namespace: nginx-ingress
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "ens3",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "10.1.0.0/16",
                         "rangeStart": "10.1.0.101",
                         "rangeEnd": "10.1.0.110",
                         "gateway": "10.1.0.1"
                    } ]
                ],
                "routes": [
                    { "dst": "10.2.0.0/16" }
                ]
            }
        }'

